apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6wyz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-6wyz@sha256:0eb3b399983dbedbb532d7b1e1e445f87861642be3859bb7febb183f46402371
        name: my-nodejs
        resources: {}
status: {}
